# ---
# - name: install system packages
#   package:
#     name:
#       - sudo

# - name: add admin user
#   user:
#     name: prints
#     password: "{{ 'iamfunky' | password_hash('sha512', 'dustysalt') }}"
#     groups:
#       - lpadmin
#     append: true

# - name: install print packages
#   package:
#     name:
#       - cups
#       - cups-bsd
#       - cups-filters
#       - foomatic-db
#       - foomatic-db-compressed-ppds
#       - printer-driver-gutenprint
#       - printer-driver-hpcups
#       - printer-driver-hpijs
#       - hpijs-ppds
#       - hp-ppd
#       - hplip
#   notify: restart_cups

- name: copy cupsd config
  copy:
    src: cupsd.conf
    dest: /etc/cups/cupsd.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart_cups

# - name: install sharing packages
#   package:
#     name:
#       - avahi-daemon
#       - samba
#   notify: restart_sharing

- name: copy smb config
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart_sharing

- name: create samba drop-in dir
  file:
    path: /etc/samba/printers
    state: directory
    owner: root
    group: root
    mode: "0755"

# - name: create spool dirs
#   file:
#     path: /var/spool/{{ item }}
#     state: directory
#     owner: root
#     group: lp
#     mode: "1755"
#   loop:
#     - samba
#     - A4

# - name: copy printer config
#   copy:
#     src: A4_printer.conf
#     dest: /etc/samba/printers/A4_printer.conf
#     owner: root
#     group: root
#     mode: "0644"
#   notify: restart_sharing




- name: check printer_list.tdb
  stat:
    path: /var/run/printer_list.tdb # https://bugzilla.redhat.com/show_bug.cgi?id=2263500
  register: printer_list

- name: trigger dcerpcd to generate printer_list.tdb
  when: not printer_list.stat.exists
  shell:
    cmd: |
      # # https://bugzilla.redhat.com/show_bug.cgi?id=2263500
      # smbclient --password= -L prints
      # rpcclient ncacn_np:prints -N -c enumprinters

      # https://wiki.archlinux.org/title/Samba#CUPS_managed_printers_are_not_listed
      /usr/libexec/samba/samba-bgqd
