---
- name: install system packages
  package:
    name:
      - sudo
      - python3-passlib

- name: enable i386 packages
  shell:
    cmd: dpkg --add-architecture i386

- name: install print packages
  package:
    name:
      - cups
      - cups-bsd
      - cups-filters
      - foomatic-db-engine
      # - foomatic-db
      - foomatic-db-compressed-ppds
      - printer-driver-gutenprint
      - printer-driver-hpcups
      - printer-driver-hpijs
      - hpijs-ppds
      - hp-ppd
      - hplip
  notify: restart_cups

- name: add admin user
  user:
    name: prints
    password: "{{ 'iamfunky' | password_hash('sha512', 'dustysalt') }}"
    groups:
      - lpadmin
    append: true

- name: copy cupsd config
  copy:
    src: cupsd.conf
    dest: /etc/cups/cupsd.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart_cups

- name: install sharing packages
  package:
    name:
      - avahi-daemon
      - samba
      - smbclient
  notify: restart_sharing

- name: create samba conf dir
  file:
    path: /etc/samba/printers
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: create samba spool dir
  file:
    path: /var/spool/samba
    state: directory
    owner: root
    group: lp
    mode: "1755"

- name: copy smb config
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart_sharing

- name: copy smb config
  copy:
    content: "[global]"
    force: false
    dest: /etc/samba/printers/printers.conf
    owner: root
    group: root
    mode: "0644"

- include_tasks: add_printer.yml
  loop: "{{ printers }}"
  vars:
    printer: "{{ item }}"

- name: check printer_list.tdb
  stat:
    path: /var/run/printer_list.tdb # https://bugzilla.redhat.com/show_bug.cgi?id=2263500
  register: printer_list

- name: trigger dcerpcd to generate printer_list.tdb
  when: not printer_list.stat.exists
  shell:
    cmd: |
      # # https://bugzilla.redhat.com/show_bug.cgi?id=2263500
      # smbclient --password= -L prints
      # rpcclient ncacn_np:prints -N -c enumprinters

      # https://wiki.archlinux.org/title/Samba#CUPS_managed_printers_are_not_listed
      /usr/libexec/samba/samba-bgqd
