---
- name: copy bash profile script
  copy:
    src: files/home/
    dest: "{{ home }}/"
    mode: "0744"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: set editor to nano
  lineinfile:
    path: /{{ home }}/.profile
    search_string: EDITOR=
    line: EDITOR=nano;    export EDITOR
