---
- name: restart_cups
  service:
    name: cups
    enabled: true
    state: restarted

- name: restart_sharing
  service:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - smbd
    - nmbd
    - avahi-daemon
